import { title } from "process";

const songs = [
  {
    number: 1,
    title: ".  All Hail the Power of Jesus' Name",
    verses: [
      "1. ALL hail the power of Jesu’s name,",
      " Let angels prostrate fall;",
      " Bring forth the royal diadem,",
      "And crown Him Lord of all.",
      "2. Crown Him, ye martyrs of your God,",
      " Who from His altar call;",
      " Extol the stem of Jesse’s rod,;",
      " And crown Him Lord of all.",
      "3. Ye chosen seed of Israel’s race,",
      " A remnant weak and small,",
      " Hail Him Who saves you by His grace,",
      " And crown Him Lord of all,",
      "4. Ye Gentile sinners, ne’er forget",
      " The wormwood and the gall;",
      "Go, spread your trophies a His feet,:",
      "And crown Him Lord of all.",
      "5. Let every kindred, every tribe,;",
      "On this terrestrial ball,",
      "To Him all majesty ascribe,",
      "And crown Him Lord of all.",
      "6. O that with yonder sacred throng",
      "We at His feet may fall,",
      "Join in the everlasting song",
      "And crown Him Lord of all.",
    ],
  },
  {
    number: 2,
    title: ". Break Thou the Bread of Life",
    verses: [
      "BREAK Thou the bread of life,",
      "Dear Lord, to me,",
      "As Thou didst break the loaves",
      "Beside the sea.",
      "Beyond the sacred page",
      "I seek Thee, Lord;",
      "My spirit pants for Thee,",
      "O Living Word!",
      "2 Break Thou the bread of life,:",
      "O Lord, to me,",
      "That hid within my heart",
      "Thy Word may be:",
      "Mould Thou each inward thought,",
      "From self set free,",
      "And let my steps be all",
      "Controlled by Thee.",
      "3 Open Thy Word of Truth,",
      "That I may see",
      "Thy message written clear",
      "And plain for me;",
      "Then in sweet fellowship",
      "Walking with Thee,",
      "Thine image on my life",
      "Engraved will be.",
      "4 Bless Thou the truth, dear Lord,",
      "To me, to me,",
      "As Thou didst bless the bread",
      "By Galilee:",
      "Then shall all bondage cease,",
      "All fetters fall;",
      "And I shall find my peace,",
      "My All in All!",
    ],
  },
  {
    number: 3,
    title: ". We Come Before Thy Throne Today",
    verses: [
      "WE come before Thy throne to-day,",
      "Thy promised presence claim;",
      "O come and enter now our hearts,",
      "And set our souls aflame.",
      "Lord, send Thy blessing, Lord, send Thy blessing,",
      "Lord, send Thy blessing on our waiting souls.",
      "2 We know that Thou art present here,",
      "Thy grace to us reveal;",
      "We fain would know Thy blessed will,",
      "Thy holy presence feel,",
      "3 0 send to us Thy quickening power,",
      "All guilt and dross remove;",
      "O let our waiting hearts be filled,",
      "Dear Saviour, with Thy love.",
      "4 Accept the homage that we bring,",
      "O Lord, we humbly pray;",
      "Bestow Thy richest blessings now,",
      "And meet with us to-day.",
    ],
  },
  {
    number: 4,
    title: ". The Name of Jesus is So Sweet",
    verses: [
      "THE name of Jesus is so sweet,",
      "I love its music to repeat;",
      "It makes my joys full and complete,",
      "The precious name of Jesus.",
      "“Jesus,” oh, how sweet the name!",
      "‘*Jesus,” every day the same;",
      "*'Jesus,” let all saints proclaim",
      "Its worthy praise for ever.",
      "2 I love the name of Him Whose heart",
      "Knows all my griefs and bears a part;",
      "Who bids all anxious fears depart—",
      "I love the name of Jesus,",
      "3 That name I fondly love to hear,",
      "It never fails my heart to cheer,",
      "Its music dries the falling tear;",
      "Exalt the name of Jesus.",
      "4 No word of man can ever tell",
      "How sweet the name I love so well;",
      "Oh, let its praises ever swell!",
      "Oh, praise the name of Jesus",
    ],
  },
  {
    number: 5,
    title: ". When Upon Life’s Billows",
    verses: [
      "WHEN upon life’s billows you are tempest tossed,",
      "When you are discouraged, thinking all is lost",
      "Count your many blessings, name them one by one,",
      "And it will surprise you what the Lord hath done.",
      "Count your blessings, name them one by one,",
      "Count your blessings, see what God hath done;",
      "Count your blessings, name them one by one,",
      "And it will surprise you what the Lord hath done.",
      "2 Are you ever burdened with a load of care?",
      "Does the cross seem-heavy you are called to bear?",
      "Count your many blessings, every doubt will fly,",
      "And you will be singing as the days go by.",
      "3 When you look at others with their lands and gold,",
      "Think that Christ has promised you His wealth untold,",
      "Count your many blessings, money cannot buy",
      "Your reward in heaven, nor your home on high.",
      "4 So amid the conflict, Whether great or small,",
      "Do not be discouraged, God is over all,",
      "Count your many blessings, angels will attend,",
      "Help and comfort give you to your journey’s end.",
    ],
  },
  {
    number: 6,
    title: ". God is Here, and That To Bless Us",
    verses: [
      "GOD is here, and that to bless us",
      "With the Spirit’s quickening power:",
      "See, the cloud already bending,",
      "Waits to drop the grateful shower.",
      "Let it come, O Lord, we pray Thee,",
      "Let the shower of blessing fall;",
      "We are waiting, we are waiting,",
      "Oh, revive the hearts of all.",
      "2 God is here! we feel His presence",
      "In this consecrated place;",
      "But we need the soul refreshing",
      "Of His free, unbounded grace.",
      "3 God is here! oh, then, believing,",
      "Bring to Him our one desire,",
      "That His love may now be kindled,",
      "Till its flame each heart inspire.",
      "4 Saviour, grant the prayer we offer,",
      "While in simple faith we bow,",
      "From the windows of Thy mercy",
      "Pour us out a bleessing now.",
    ],
  },
  {
    number: 7,
    title: ". To God be the Glory",
    verses: [
      "TO God be the glory, great things He hath done,",
      "So loved He the world that He gave us His Son,",
      "Who yielded His life an atonement for sin,",
      "And opened the Life Gate that all may o in.",
      "Praise the Lord, praise the Lord,",
      "Let the earth hear His voice;",
      "Praise the Lord, praise the Lord,",
      "Let the people rejoice.",
      "O come to the Father, through Jesus the Son,",
      "And give Hin the glory, great things He hath done.",
      "2 0 perfect redemption, the purchase of blood,",
      "To every believer the promise of God;",
      "The vilest offender who truly believes,",
      "That moment from Jesus a pardon receives.",
      "3 Great things He hath taught us, great things He hath done,",
      "And great our rejoicing through Jesus the Son;",
      "But purer, and higher, and greater will be-",
      "Our wonder, our transport when Jesus we see,",
    ],
  },
  {
    number: 8,
    title: ". Who is on the Lord's Side?",
    verses: [
      "WHO is on the Lord’s side?",
      "Who will serve the King?",
      "Who will be His helpers,",
      "Other lives to bring?",
      "Who will leave the world’s side?",
      "Who will face the foe?",

      "Who is on the Lord’s side",
      "Who for Him will go?",
      "By Thy call of mercy,",

      "By Thy grace divine,",
      "We are on the Lord's side,",
      "Saviour, we are Thine!",
      "2 Not for weight of glory,",
      "Not for crown and palm,",
      "Enter we the army,",
      "Raise the warrior psalm;",
      "But for love that claimeth",
      "Lives for whom He died:",
      "He whom Jesus nameth",
      "Must be on His side!",
      "By Thy love constraining,",
      "By Thy grace divine,",
      "We are on the Lord’s side,",
      "Saviour, we are Thine!",
      "3 Jesus, Thou hast bought us,",
      "Not with gold or gem,",
      "But with Thine own life-blood",
      "For Thy diadem;",
      "With Thy blessing filling",
      "All who come to Thee,",
      "Thou hast made us willing,",
      "Thou hast made us free.",
      "By Thy grand redemption,",
      "By Thy grace divine,",
      "We are on the Lord’s side,",
      "Saviour, we are Thine!",
      "4 Fierce may be the conflict,",
      "Strong may be the foe;",
      "But the King’s own army",
      "None can overthrow:",
      "Round His standard ranging,",
      "Victory is secure,",
      "For His truth unchanging",
      "Makes the triumph sure,",
      "Joyfully enlisting,",
      "By Thy grace divine,",
      "We are on the Lord’s side",
      "Saviour, we are Thine!",
    ],
  },
  {
    number: 9,
    title: ". I Must Have the Saviour With Me",
    verses: [
      "I MUST have the Saviour with me",
      "For I dare not walk alone,",
      "I must feel His presence near me,",
      "And His arm around me thrown,",
      "Then my soul ... shall fear no ill ...,",
      "Let Him lead .... me where He will ...",
      "I will go without a murmur,",
      "And His footsteps follow still.",
      "2 I must have the Saviour with me",
      "For my faith, at best, is weak",
      "He can whisper words of comfort",
      "That no other voice can speak.",
      "3 I must have the Saviour with me",
      "In the onward march of life,",
      "Through the tempest and the sunshine",
      "Through the battle and the strife",
      "4 I must have the Saviour with me",
      "And His eye the way must guide",
      "Till I reach the vale of Jordan",
      "Till I cross the rolling tide",
    ],
  },
  {
    number: 10,
    title: "Here in Thy Name We are Gathered",
    verses: [
      "HERE in Thy name we are gathered,",
      "Come and revive us, O Lord;",
      "There shall be showers of blessing,",
      "Thou hast declared in Thy word.",
      "Oh, graciously hear us,",
      "Graciously hear us, we pray",
      "Pour from Thy windows upon us",
      "Showers of blessing to-day.",
      "2 Oh! that the showers of blessing",
      "Now on our sows may descend,",
      "While at the footstool of mercy",
      "Pleading Thy promise we bend!",
      "3 There shall be showers of blessing,",
      "Promise that never can fail;",
      "Thou wilt regard our petition;",
      "Surely our faith will prevail.",
      "4 Showers of blessing, we need them,",
      "Showers of blessing from Thee;",
      "Showers of blessing, oh, grant them,",
      "Thine all the glory shall be.",
    ],
  },
];

export default songs;
