const songs = [
  {
    number: 1,
    title: "All Hail the Power of Jesus' Name",
    verses: [
      { line: "1 ALL hail the power of Jesu's name,", type: "verse" },
      { line: " Let angels prostrate fall;", type: "verse" },
      { line: " Bring forth the royal diadem,", type: "verse" },
      { line: "And crown Him Lord of all.", type: "verse" },
      { line: "2 Crown Him, ye martyrs of your God,", type: "verse" },
      { line: " Who from His altar call;", type: "verse" },
      { line: " Extol the stem of Jesse's rod,;", type: "verse" },
      { line: " And crown Him Lord of all.", type: "verse" },
      { line: "3 Ye chosen seed of Israel's race,", type: "verse" },
      { line: " A remnant weak and small,", type: "verse" },
      { line: " Hail Him Who saves you by His grace,", type: "verse" },
      { line: " And crown Him Lord of all,", type: "verse" },
      { line: "4 Ye Gentile sinners, ne'er forget", type: "verse" },
      { line: " The wormwood and the gall;", type: "verse" },
      { line: "Go, spread your trophies at His feet,:", type: "verse" },
      { line: "And crown Him Lord of all.", type: "verse" },
      { line: "5 Let every kindred, every tribe,;", type: "verse" },
      { line: "On this terrestrial ball,", type: "verse" },
      { line: "To Him all majesty ascribe,", type: "verse" },
      { line: "And crown Him Lord of all.", type: "verse" },
      { line: "6 O that with yonder sacred throng", type: "verse" },
      { line: "We at His feet may fall,", type: "verse" },
      { line: "Join in the everlasting song", type: "verse" },
      { line: "And crown Him Lord of all.", type: "verse" },
    ],
  },
  {
    number: 2,
    title: "Break Thou the Bread of Life",
    verses: [
      { line: "1 BREAK Thou the bread of life,", type: "verse" },
      { line: "Dear Lord, to me,", type: "verse" },
      { line: "As Thou didst break the loaves", type: "verse" },
      { line: "Beside the sea.", type: "verse" },
      { line: "Beyond the sacred page", type: "verse" },
      { line: "I seek Thee, Lord;", type: "verse" },
      { line: "My spirit pants for Thee,", type: "verse" },
      { line: "O Living Word!", type: "verse" },
      { line: "2 Break Thou the bread of life,", type: "verse" },
      { line: "O Lord, to me,", type: "verse" },
      { line: "That hid within my heart", type: "verse" },
      { line: "Thy Word may be:", type: "verse" },
      { line: "Mould Thou each inward thought,", type: "verse" },
      { line: "From self set free,", type: "verse" },
      { line: "And let my steps be all", type: "verse" },
      { line: "Controlled by Thee.", type: "verse" },
      { line: "3 Open Thy Word of Truth,", type: "verse" },
      { line: "That I may see", type: "verse" },
      { line: "Thy message written clear", type: "verse" },
      { line: "And plain for me;", type: "verse" },
      { line: "Then in sweet fellowship", type: "verse" },
      { line: "Walking with Thee,", type: "verse" },
      { line: "Thine image on my life", type: "verse" },
      { line: "Engraved will be.", type: "verse" },
      { line: "4 Bless Thou the truth, dear Lord,", type: "verse" },
      { line: "To me, to me,", type: "verse" },
      { line: "As Thou didst bless the bread", type: "verse" },
      { line: "By Galilee:", type: "verse" },
      { line: "Then shall all bondage cease,", type: "verse" },
      { line: "All fetters fall;", type: "verse" },
      { line: "And I shall find my peace,", type: "verse" },
      { line: "My All in All!", type: "verse" },
    ],
  },
  {
    number: 3,
    title: "We Come Before Thy Throne Today",
    verses: [
      { line: "1 WE come before Thy throne to-day,", type: "verse" },
      { line: "Thy promised presence claim;", type: "verse" },
      { line: "O come and enter now our hearts,", type: "verse" },
      { line: "And set our souls aflame.", type: "verse" },
      {
        line: "Lord, send Thy blessing, Lord, send Thy blessing,",
        type: "chorus",
      },
      { line: "Lord, send Thy blessing on our waiting souls.", type: "chorus" },
      { line: "2 We know that Thou art present here,", type: "verse" },
      { line: "Thy grace to us reveal;", type: "verse" },
      { line: "We fain would know Thy blessed will,", type: "verse" },
      { line: "Thy holy presence feel,", type: "verse" },
      { line: "3 0 send to us Thy quickening power,", type: "verse" },
      { line: "All guilt and dross remove;", type: "verse" },
      { line: "O let our waiting hearts be filled,", type: "verse" },
      { line: "Dear Saviour, with Thy love.", type: "verse" },
      { line: "4 Accept the homage that we bring,", type: "verse" },
      { line: "O Lord, we humbly pray;", type: "verse" },
      { line: "Bestow Thy richest blessings now,", type: "verse" },
      { line: "And meet with us to-day.", type: "verse" },
    ],
  },
  {
    number: 4,
    title: "The Name of Jesus is So Sweet",
    verses: [
      { line: "1 THE name of Jesus is so sweet,", type: "verse" },
      { line: "I love its music to repeat;", type: "verse" },
      { line: "It makes my joys full and complete,", type: "verse" },
      { line: "The precious name of Jesus.", type: "verse" },
      { line: "“Jesus,” oh, how sweet the name!", type: "chorus" },
      { line: "Jesus,” every day the same;", type: "chorus" },
      { line: "Jesus,” let all saints proclaim", type: "chorus" },
      { line: "Its worthy praise for ever.", type: "chorus" },
      { line: "2 I love the name of Him Whose heart", type: "verse" },
      { line: "Knows all my griefs and bears a part;", type: "verse" },
      { line: "Who bids all anxious fears depart—", type: "verse" },
      { line: "I love the name of Jesus,", type: "verse" },
      { line: "3 That name I fondly love to hear,", type: "verse" },
      { line: "It never fails my heart to cheer,", type: "verse" },
      { line: "Its music dries the falling tear;", type: "verse" },
      { line: "Exalt the name of Jesus.", type: "verse" },
      { line: "4 No word of man can ever tell", type: "verse" },
      { line: "How sweet the name I love so well;", type: "verse" },
      { line: "Oh, let its praises ever swell!", type: "verse" },
      { line: "Oh, praise the name of Jesus", type: "verse" },
    ],
  },
  {
    number: 5,
    title: "When Upon Life's Billows",
    verses: [
      {
        line: "1 WHEN upon life's billows you are tempest tossed,",
        type: "verse",
      },
      { line: "When you are discouraged, thinking all is lost", type: "verse" },
      {
        line: "Count your many blessings, name them one by one,",
        type: "verse",
      },
      {
        line: "And it will surprise you what the Lord hath done.",
        type: "verse",
      },
      { line: "Count your blessings, name them one by one,", type: "chorus" },
      { line: "Count your blessings, see what God hath done;", type: "chorus" },
      { line: "Count your blessings, name them one by one,", type: "chorus" },
      {
        line: "And it will surprise you what the Lord hath done.",
        type: "chorus",
      },
      { line: "2 Are you ever burdened with a load of care?", type: "verse" },
      {
        line: "Does the cross seem-heavy you are called to bear?",
        type: "verse",
      },
      {
        line: "Count your many blessings, every doubt will fly,",
        type: "verse",
      },
      { line: "And you will be singing as the days go by.", type: "verse" },
      {
        line: "3 When you look at others with their lands and gold,",
        type: "verse",
      },
      {
        line: "Think that Christ has promised you His wealth untold,",
        type: "verse",
      },
      { line: "Count your many blessings, money cannot buy", type: "verse" },
      { line: "Your reward in heaven, nor your home on high.", type: "verse" },
      {
        line: "4 So amid the conflict, Whether great or small,",
        type: "verse",
      },
      { line: "Do not be discouraged, God is over all,", type: "verse" },
      { line: "Count your many blessings, angels will attend,", type: "verse" },
      {
        line: "Help and comfort give you to your journey's end.",
        type: "verse",
      },
    ],
  },
  {
    number: 6,
    title: "God is Here, and That To Bless Us",
    verses: [
      { line: "1 GOD is here, and that to bless us", type: "verse" },
      { line: "With the Spirit's quickening power:", type: "verse" },
      { line: "See, the cloud already bending,", type: "verse" },
      { line: "Waits to drop the grateful shower.", type: "verse" },
      { line: "Let it come, O Lord, we pray Thee,", type: "chorus" },
      { line: "Let the shower of blessing fall;", type: "chorus" },
      { line: "We are waiting, we are waiting,", type: "chorus" },
      { line: "Oh, revive the hearts of all.", type: "chorus" },
      { line: "2 God is here! we feel His presence", type: "verse" },
      { line: "In this consecrated place;", type: "verse" },
      { line: "But we need the soul refreshing", type: "verse" },
      { line: "Of His free, unbounded grace.", type: "verse" },
      { line: "3 God is here! oh, then, believing,", type: "verse" },
      { line: "Bring to Him our one desire,", type: "verse" },
      { line: "That His love may now be kindled,", type: "verse" },
      { line: "Till its flame each heart inspire.", type: "verse" },
      { line: "4 Saviour, grant the prayer we offer,", type: "verse" },
      { line: "While in simple faith we bow,", type: "verse" },
      { line: "From the windows of Thy mercy", type: "verse" },
      { line: "Pour us out a blessing now.", type: "verse" },
    ],
  },
  {
    number: 7,
    title: "To God be the Glory",
    verses: [
      {
        line: "1 TO God be the glory, great things He hath done,",
        type: "verse",
      },
      { line: "So loved He the world that He gave us His Son,", type: "verse" },
      { line: "Who yielded His life an atonement for sin,", type: "verse" },
      { line: "And opened the Life Gate that all may go in.", type: "verse" },
      { line: "Praise the Lord, praise the Lord,", type: "chorus" },
      { line: "Let the earth hear His voice;", type: "chorus" },
      { line: "Praise the Lord, praise the Lord,", type: "chorus" },
      { line: "Let the people rejoice.", type: "chorus" },
      { line: "O come to the Father, through Jesus the Son,", type: "chorus" },
      {
        line: "And give Him the glory, great things He hath done.",
        type: "chorus",
      },
      { line: "2 O perfect redemption, the purchase of blood,", type: "verse" },
      { line: "To every believer the promise of God;", type: "verse" },
      { line: "The vilest offender who truly believes,", type: "verse" },
      { line: "That moment from Jesus a pardon receives.", type: "verse" },
      {
        line: "3 Great things He hath taught us, great things He hath done,",
        type: "verse",
      },
      { line: "And great our rejoicing through Jesus the Son;", type: "verse" },
      { line: "But purer, and higher, and greater will be-", type: "verse" },
      { line: "Our wonder, our transport when Jesus we see,", type: "verse" },
    ],
  },
  {
    number: 8,
    title: "Who is on the Lord's Side?",
    verses: [
      { line: "1 WHO is on the Lord's side?", type: "verse" },
      { line: "Who will serve the King?", type: "verse" },
      { line: "Who will be His helpers,", type: "verse" },
      { line: "Other lives to bring?", type: "verse" },
      { line: "Who will leave the world's side?", type: "verse" },
      { line: "Who will face the foe?", type: "verse" },
      { line: "Who is on the Lord's side", type: "chorus" },
      { line: "Who for Him will go?", type: "chorus" },
      { line: "By Thy call of mercy,", type: "chorus" },
      { line: "By Thy grace divine,", type: "chorus" },
      { line: "We are on the Lord's side,", type: "chorus" },
      { line: "Saviour, we are Thine!", type: "chorus" },
      { line: "2 Not for weight of glory,", type: "verse" },
      { line: "Not for crown and palm,", type: "verse" },
      { line: "Enter we the army,", type: "verse" },
      { line: "Raise the warrior psalm;", type: "verse" },
      { line: "But for love that claimeth", type: "verse" },
      { line: "Lives for whom He died:", type: "verse" },
      { line: "He whom Jesus nameth", type: "verse" },
      { line: "Must be on His side!", type: "verse" },
      { line: "By Thy love constraining,", type: "chorus" },
      { line: "By Thy grace divine,", type: "chorus" },
      { line: "We are on the Lord's side,", type: "chorus" },
      { line: "Saviour, we are Thine!", type: "chorus" },
      { line: "3 Jesus, Thou hast bought us,", type: "verse" },
      { line: "Not with gold or gem,", type: "verse" },
      { line: "But with Thine own life-blood", type: "verse" },
      { line: "For Thy diadem;", type: "verse" },
      { line: "With Thy blessing filling", type: "verse" },
      { line: "All who come to Thee,", type: "verse" },
      { line: "Thou hast made us willing,", type: "verse" },
      { line: "Thou hast made us free.", type: "verse" },
      { line: "By Thy grand redemption,", type: "chorus" },
      { line: "By Thy grace divine,", type: "chorus" },
      { line: "We are on the Lord's side,", type: "chorus" },
      { line: "Saviour, we are Thine!", type: "chorus" },
      { line: "4 Fierce may be the conflict,", type: "verse" },
      { line: "Strong may be the foe;", type: "verse" },
      { line: "But the King's own army", type: "verse" },
      { line: "None can overthrow:", type: "verse" },
      { line: "Round His standard ranging,", type: "verse" },
      { line: "Victory is secure,", type: "verse" },
      { line: "For His truth unchanging", type: "verse" },
      { line: "Makes the triumph sure,", type: "verse" },
      { line: "Joyfully enlisting,", type: "chorus" },
      { line: "By Thy grace divine,", type: "chorus" },
      { line: "We are on the Lord's side", type: "chorus" },
      { line: "Saviour, we are Thine!", type: "chorus" },
    ],
  },
  {
    number: 9,
    title: "I Must Have the Saviour With Me",
    verses: [
      { line: "1 I MUST have the Saviour with me", type: "verse" },
      { line: "For I dare not walk alone,", type: "verse" },
      { line: "I must feel His presence near me,", type: "verse" },
      { line: "And His arm around me thrown,", type: "verse" },
      { line: "Then my soul ... shall fear no ill ...,", type: "verse" },
      { line: "Let Him lead .... me where He will ...", type: "verse" },
      { line: "I will go without a murmur,", type: "verse" },
      { line: "And His footsteps follow still.", type: "verse" },
      { line: "2 I must have the Saviour with me", type: "verse" },
      { line: "For my faith, at best, is weak", type: "verse" },
      { line: "He can whisper words of comfort", type: "verse" },
      { line: "That no other voice can speak.", type: "verse" },
      { line: "3 I must have the Saviour with me", type: "verse" },
      { line: "In the onward march of life,", type: "verse" },
      { line: "Through the tempest and the sunshine", type: "verse" },
      { line: "Through the battle and the strife", type: "verse" },
      { line: "4 I must have the Saviour with me", type: "verse" },
      { line: "And His eye the way must guide", type: "verse" },
      { line: "Till I reach the vale of Jordan", type: "verse" },
      { line: "Till I cross the rolling tide", type: "verse" },
    ],
  },
  {
    number: 10,
    title: "Here in Thy Name We are Gathered",
    verses: [
      { line: "1 HERE in Thy name we are gathered,", type: "verse" },
      { line: "Come and revive us, O Lord;", type: "verse" },
      { line: "There shall be showers of blessing,", type: "verse" },
      { line: "Thou hast declared in Thy word.", type: "verse" },
      { line: "Oh, graciously hear us,", type: "chorus" },
      { line: "Graciously hear us, we pray", type: "chorus" },
      { line: "Pour from Thy windows upon us", type: "chorus" },
      { line: "Showers of blessing to-day.", type: "chorus" },
      { line: "2 Oh! that the showers of blessing", type: "verse" },
      { line: "Now on our souls may descend,", type: "verse" },
      { line: "While at the footstool of mercy", type: "verse" },
      { line: "Pleading Thy promise we bend!", type: "verse" },
      { line: "3 There shall be showers of blessing,", type: "verse" },
      { line: "Promise that never can fail;", type: "verse" },
      { line: "Thou wilt regard our petition;", type: "verse" },
      { line: "Surely our faith will prevail.", type: "verse" },
      { line: "4 Showers of blessing, we need them,", type: "verse" },
      { line: "Showers of blessing from Thee;", type: "verse" },
      { line: "Showers of blessing, oh, grant them,", type: "verse" },
      { line: "Thine all the glory shall be.", type: "verse" },
    ],
  },
  {
    number: 11,
    title: "My Song Shall Be of Jesus",
    verses: [
      { line: "1 MY song shall be of Jesus,", type: "verse" },
      { line: "His mercy crowns my days,", type: "verse" },
      { line: "He fills my cup with blessings,", type: "verse" },
      { line: "And tunes my heart to praise;", type: "verse" },
      { line: "My song shall be of Jesus,", type: "verse" },
      { line: "The precious Lamb of God,", type: "verse" },
      { line: "Who gave Himself my ransom,", type: "verse" },
      { line: "And bought me with His blood.", type: "verse" },
      { line: "2 My song shall be of Jesus,", type: "verse" },
      { line: "When sitting at His feet,", type: "verse" },
      { line: "I call to mind His goodness,", type: "verse" },
      { line: "In meditation sweet:", type: "verse" },
      { line: "My song shall be of Jesus,", type: "verse" },
      { line: "Whatever ill betide;", type: "verse" },
      { line: "I'll sing the grace that saves me,", type: "verse" },
      { line: "And keeps me at His side,", type: "verse" },
      { line: "3 My song shall be of Jesus,", type: "verse" },
      { line: "While pressing on my way,", type: "verse" },
      { line: "To reach the blissful region", type: "verse" },
      { line: "Of pure and perfect day;", type: "verse" },
      { line: "And when my soul shall enter", type: "verse" },
      { line: "The gate of Eden fair,", type: "verse" },
      { line: "A song of praise to Jesus", type: "verse" },
      { line: "I'll sing for ever there.", type: "verse" },
    ],
  },
  {
    number: 12,
    title: "Praise Him, Jesus Our Blessed Redeemer",
    verses: [
      {
        line: "1 PRAISE Him, praise Him, Jesus, our blessed Redeemer,",
        type: "verse",
      },
      { line: "Sing, O earth, His wonderful love proclaim,", type: "verse" },
      {
        line: "Hail Him! hail Him! highest archangels in glory,",
        type: "verse",
      },
      { line: "Strength and honour give to His holy name.", type: "verse" },
      { line: "Like a shepherd Jesus will guard His children,", type: "verse" },
      { line: "In His arms He carries them all day long.", type: "verse" },
      {
        line: "O ye saints that dwell on the mountain of Zion,",
        type: "verse",
      },
      { line: "Praise Him! praise Him! ever in joyful song.", type: "verse" },
      {
        line: "2 Praise Him, praise Him, Jesus, our blessed Redeemer,",
        type: "verse",
      },
      { line: "For our sins He suffered and bled and died;", type: "verse" },
      { line: "He, our rock, our hope of eternal salvation,", type: "verse" },
      { line: "Hail Him! hail Him! Jesus the crucified.", type: "verse" },
      { line: "Loving Saviour, meekly enduring sorrow,", type: "verse" },
      {
        line: "Crowned with thorns that cruelly pierced His brow;",
        type: "verse",
      },
      { line: "Once for us rejected, despised, and forsaken,", type: "verse" },
      { line: "Prince of Glory, ever triumphant now.", type: "verse" },
      {
        line: "3 Praise Him, praise Him, Jesus, our blessed Redeemer,",
        type: "verse",
      },
      { line: "Heavenly portals, loud with hosannahs ring,", type: "verse" },
      { line: "Jesus, Saviour, reigneth for ever and ever,", type: "verse" },
      {
        line: "Crown Him, crown Him, Prophet and Priest and King!",
        type: "verse",
      },
      {
        line: "Death is vanquished! tell it with joy ye faithful,",
        type: "verse",
      },
      { line: "Where is now thy victory, boasting grave?", type: "verse" },
      {
        line: "Jesus lives! no longer thy portals are cheerless,",
        type: "verse",
      },
      { line: "Jesus lives, the mighty and strong to save.", type: "verse" },
    ],
  },
  {
    number: 13,
    title: "Standing on the Promises of Christ",
    verses: [
      { line: "1 STANDING on the promises of Christ our King,", type: "verse" },
      { line: "Through eternal ages let His praises ring:", type: "verse" },
      { line: "Glory in the highest, I will shout and sing,", type: "verse" },
      { line: "Standing on the promises of God.", type: "verse" },
      { line: "Stand....ing, stand....ing,", type: "chorus" },
      { line: "Standing on the promises of God my Saviour,", type: "chorus" },
      { line: "Stand....ing, stand....ing,", type: "chorus" },
      { line: "I'm standing on the promises of God.", type: "chorus" },
      { line: "2 Standing on the promises that cannot fail,", type: "verse" },
      {
        line: "When the howling storms of doubt and fear assail,",
        type: "verse",
      },
      { line: "By the living word of God I shall prevail,", type: "verse" },
      { line: "Standing on the promises of God.", type: "verse" },
      { line: "3 Standing on the promises I now can see", type: "verse" },
      {
        line: "Perfect, present cleansing in the blood for me;",
        type: "verse",
      },
      {
        line: "Standing in the liberty where Christ makes free,",
        type: "verse",
      },
      { line: "Standing on the promises of God.", type: "verse" },
      { line: "4 Standing on the promises of Christ the Lord", type: "verse" },
      { line: "Bound to Him eternally by love's strong cord,", type: "verse" },
      { line: "Overcoming daily with the Spirit's sword,", type: "verse" },
      { line: "Standing on the promises of God.", type: "verse" },
    ],
  },
  {
    number: 14,
    title: "The Wondrous Work the Lord Has Done",
    verses: [
      { line: "1 THE wondrous work the Lord has done", type: "verse" },
      { line: "Let every voice proclaim!", type: "verse" },
      { line: "And for the work of grace begun;", type: "verse" },
      { line: "The wondrous battle fought and won,", type: "verse" },
      { line: "Give glory to His name!", type: "verse" },
      { line: "We pleaded for the Spirit,", type: "verse" },
      { line: "He came in mighty power!", type: "verse" },
      { line: "We pleaded for the droppings,", type: "verse" },
      { line: "And, lo, He sent the shower!", type: "verse" },
      { line: "2 Unto the Lord doth praise belong", type: "verse" },
      { line: "O tell it everywhere!", type: "verse" },
      { line: "Let every ransomed soul prolong", type: "verse" },
      { line: "The loud hosannah of the song", type: "verse" },
      { line: "The Lord doth answer prayer!", type: "verse" },
      { line: "3 We'll sing the power of Jesus' name,", type: "verse" },
      { line: "And His atoning blood;", type: "verse" },
      { line: "To-day and evermore the same,", type: "verse" },
      { line: "The vilest sinner to reclaim,", type: "verse" },
      { line: "And bring him back to God.", type: "verse" },
      { line: "4 Let every heart and every tongue", type: "verse" },
      { line: "As one united host", type: "verse" },
      { line: "Praise God for what His arm hath done", type: "verse" },
      { line: "Praise God the Father, God the Son,", type: "verse" },
      { line: "And God the Holy Ghost", type: "verse" },
    ],
  },
  {
    number: 15,
    title: "Come, O My Soul",
    verses: [
      { line: "1 COME, O my soul, my every power awaking,", type: "verse" },
      { line: "Look unto Him whose goodness crowns thy days;", type: "verse" },
      { line: "While into song angelic choirs are breaking,", type: "verse" },
      { line: "O let thy voice its thankful tribute raise,", type: "verse" },
      { line: "Tell how alone the path of death He trod;", type: "verse" },
      { line: "Tell how He lives, thine Advocate with God;", type: "verse" },
      {
        line: "Lift up thy voice, while heaven's triumphant throng",
        type: "verse",
      },
      { line: "Swell at His feet the everlasting song.", type: "verse" },
      {
        line: "2 Think O my soul, how patiently He sought thee,",
        type: "verse",
      },
      { line: "Far, far away upon the mountains steep,", type: "verse" },
      { line: "Then in His arms how tenderly He brought thee,", type: "verse" },
      { line: "Home to His fold a weary, wandering sheep.", type: "verse" },
      { line: "3 Sing, O my soul, and let thy pure devotion", type: "verse" },
      {
        line: "Rise to His throne, thy Sayiour, Friend, and Guide;",
        type: "verse",
      },
      { line: "Sing of His love, that, like a mighty ocean,", type: "verse" },
      { line: "Flows unto thee, and all the world beside.", type: "verse" },
      {
        line: "4 Soon, O my soul, thine earthly house forsaking,",
        type: "verse",
      },
      { line: "Soon shalt thou rise the better land to see", type: "verse" },
      { line: "Then will thy harp, a nobler strain awaking,", type: "verse" },
      { line: "Praise Him who died to purchase life for thee.", type: "verse" },
    ],
  },
  {
    number: 16,
    title: "O Love That Wilt Not Let Me Go",
    verses: [
      { line: "1  O LOVE, that wilt not let me go,", type: "verse" },
      { line: "I rest my weary soul in Thee;", type: "verse" },
      { line: "I give Thee back the life I owe,", type: "verse" },
      { line: "That in Thine ocean depths, its flow", type: "verse" },
      { line: "May richer, fuller be.", type: "verse" },
      { line: "2 O Light, that followest all my way,", type: "verse" },
      { line: "I yield my flickering torch to Thee;", type: "verse" },
      { line: "My heart restores its borrowed ray,", type: "verse" },
      { line: "That in Thy sunshine's blaze, its day", type: "verse" },
      { line: "May brighter, fairer be.", type: "verse" },
      { line: "3 O Joy, that seekest me through pain,", type: "verse" },
      { line: "I cannot close my heart to Thee;", type: "verse" },
      { line: "I trace the rainbow through the rain,", type: "verse" },
      { line: "And feel the promise is not vain,", type: "verse" },
      { line: "That morn shall tearless be.", type: "verse" },
      { line: "4 O Cross, that liftest up my head,", type: "verse" },
      { line: "I dare not ask to fly from Thee;", type: "verse" },
      { line: "I lay in dust life's glory dead", type: "verse" },
      { line: "And from the ground, there blossoms red", type: "verse" },
      { line: "Life that shall endless be.", type: "verse" },
    ],
  },
  {
    number: 17,
    title: "I Will sing of my Redeemer",
    verses: [
      { line: "1 I WILL sing of me Redeemer", type: "verse" },
      { line: "And His wondrous love to me:", type: "verse" },
      { line: "On the cruel cross He suffered,", type: "verse" },
      { line: "From the curse to set me free.", type: "verse" },
      { line: "Sing, oh sing....of my Redeemer:", type: "chorus" },
      { line: "With His blood... He purchased me...", type: "chorus" },
      { line: "One the cross... He sealed my pardon...", type: "chorus" },
      { line: "Paid the debt... and made me free...", type: "chorus" },
      { line: "2 I will tell the wondrous story,", type: "verse" },
      { line: "How my lost estate to save,", type: "verse" },
      { line: "In His boundless love and mercy,", type: "verse" },
      { line: "He the ransom freély gave.", type: "verse" },
      { line: "3 I will praise my dear Redeemer,", type: "verse" },
      { line: "His triumphant power I'll tell", type: "verse" },
      { line: "How the victory He giveth,", type: "verse" },
      { line: "Over sin, and death, and hell.", type: "verse" },
      { line: "4 I will sing of my Redeemer,", type: "verse" },
      { line: "And His heavenly love to me", type: "verse" },
      { line: "He from death to life hath brought me,", type: "verse" },
      { line: "Son of God, with Him to be.", type: "verse" },
    ],
  },
  {
    number: 18,
    title: "The God of Abraham Praise",
    verses: [
      { line: "1 THE God of Abraham praise", type: "verse" },
      { line: "Who reigns enthroned above", type: "verse" },
      { line: "Ancient of everlasting days,", type: "verse" },
      { line: "And God of love!", type: "verse" },
      { line: "Jehovah! great I AM!", type: "verse" },
      { line: "By earth and heaven confest,", type: "verse" },
      { line: "I bow, and bless the sacred Name", type: "verse" },
      { line: "For ever blest.", type: "verse" },
      { line: "2 The God of Abraham praise,", type: "verse" },
      { line: "At whose supreme command", type: "verse" },
      { line: "From earth I rise, and seek the joys", type: "verse" },
      { line: "At His right hand.", type: "verse" },
      { line: "I all on earth forsake,", type: "verse" },
      { line: "Its wisdom, fame, and power", type: "verse" },
      { line: "And Him my only portion make", type: "verse" },
      { line: "My shield and tower.", type: "verse" },
      { line: "3 He by Himself hath sworn;", type: "verse" },
      { line: "I on His oath depend;", type: "verse" },
      { line: "I shall, on eagles' wings upborne", type: "verse" },
      { line: "To heaven ascend.", type: "verse" },
      { line: "I shall behold His face,", type: "verse" },
      { line: "I shall His power adore,", type: "verse" },
      { line: "And sing the wonders of His grace", type: "verse" },
      { line: "For evermore.", type: "verse" },
      { line: "4 There dwell the Lord our King,", type: "verse" },
      { line: "The Lord our righteousness,", type: "verse" },
      { line: "Triumphant o'er the world and sin:", type: "verse" },
      { line: "The Prince of Peace.", type: "verse" },
      { line: "On Zion's sacred height", type: "verse" },
      { line: "His kingdom still maintains,", type: "verse" },
      { line: "And glorious with His saints in light,", type: "verse" },
      { line: "For ever reigns.", type: "verse" },
      { line: "The whole triumphant host,", type: "verse" },
      { line: "Give thanks to God on high;", type: "verse" },
      { line: "'Hail, Father, Son, and Holy Ghost!'", type: "verse" },
      { line: "They ever cry,", type: "verse" },
      { line: "Hail Abrahams's God and mine!", type: "verse" },
      { line: "I join the heavenly lays:", type: "verse" },
      { line: "All might and majesty are Thine", type: "verse" },
      { line: "And endless praise.", type: "verse" },
    ],
  },
  {
    number: 19,
    title: "My Shepherd is the Lamb",
    verses: [
      { line: "1 MY Shepherd is the Lamb,", type: "verse" },
      { line: "The living Lord, who died;", type: "verse" },
      { line: "With all things good I ever am", type: "verse" },
      { line: "By Him supplied", type: "verse" },
      { line: "He richly feeds my soul", type: "verse" },
      { line: "With blessings from above,", type: "verse" },
      { line: "And leads me where the rivers roll", type: "verse" },
      { line: "Of endless love", type: "verse" },
      { line: "2 My soul He doth restore", type: "verse" },
      { line: "Whene'er I go astray;", type: "verse" },
      { line: "He makes my cup of joy run o'er", type: "verse" },
      { line: "From day to day;", type: "verse" },
      { line: "His love, so full, so free,", type: "verse" },
      { line: "Anoints my head with oil;", type: "verse" },
      { line: "Mercy and goodness follow me,", type: "verse" },
      { line: "Fruit of His toil.", type: "verse" },
      { line: "3 When faith and hope shall cease,", type: "verse" },
      { line: "And love abide alone,", type: "verse" },
      { line: "Then shall I see Him face to face,", type: "verse" },
      { line: "And know as known.", type: "verse" },
      { line: "Still shall I lift my voice,", type: "verse" },
      { line: "His praise my shall be;", type: "verse" },
      { line: "And I will in His love rejoice", type: "verse" },
      { line: "Who died for me.", type: "verse" },
    ],
  },
  {
    number: 20,
    title: "With Harps and With Vials",
    verses: [
      {
        line: "1 WITH harps and with vials there stand a great throng",
        type: "verse",
      },
      {
        line: "In the presence of Jesus and sing this new song.",
        type: "verse",
      },
      {
        line: "Unto Him Who hath loved us and washed us from sin,",
        type: "chorus",
      },
      { line: "Unto Him be the glory for ever! Amen!", type: "chorus" },
      {
        line: "2 All these once were sinners, defiled in His sight,",
        type: "verse",
      },
      {
        line: "Now arrayed in pure garments in praise they unite.",
        type: "verse",
      },
      { line: "3. He maketh the rebel a priest and a king,", type: "verse" },
      {
        line: "He hath bought us and taugh us this song to sing.",
        type: "verse",
      },
      {
        line: "4 How helpless and hopeless we sinners had been,",
        type: "verse",
      },
      {
        line: "If He never had loved us till clensed from our sin?",
        type: "verse",
      },
      { line: "5 Aloud in His praises our voices shall ring,", type: "verse" },
      {
        line: "So that others, believing this new song shall sing.",
        type: "verse",
      },
    ],
  },
  {
    number: 21,
    title: "Hark, Hark, My Soul!",
    verses: [
      {
        line: "1 HARK, hark, my soul! angelic songs are swelling",
        type: "verse",
      },
      {
        line: "O'er earth's green fields and ocean's wave-beat shore:",
        type: "verse",
      },
      {
        line: "How sweet the truth those blessed strains are telling",
        type: "verse",
      },
      { line: "Of that new life when sin shall be no more!", type: "verse" },
      { line: "Angels of Jesus, angels of light,", type: "chorus" },
      { line: "Singing to welcome the pilgrims of the night!", type: "chorus" },
      {
        line: "2 Onward we go, for still we hear them singing,",
        type: "verse",
      },
      { line: "'Come, weary souls, for Jesus bids you come:'", type: "verse" },
      {
        line: "And, through the dark, its echoes sweetly ringing,",
        type: "verse",
      },
      { line: "The music of the gospel leads us home:", type: "verse" },
      {
        line: "3 Far, far away, like bells at evening pealing,",
        type: "verse",
      },
      { line: "The voice of Jesus sounds o'er land and sea,", type: "verse" },
      { line: "And laden souls, by thousands meekly stealing,", type: "verse" },
      { line: "Kind Shepherd, turn their weary steps to Thee:", type: "verse" },
      {
        line: "4 Angels, sing on, your faithful watches keeping;",
        type: "verse",
      },
      { line: "Sing us sweet fragments of the songs above.", type: "verse" },
      {
        line: "Till morning's joy shall end the night of weeping,",
        type: "verse",
      },
      {
        line: "And life's long shadows break in cloudless love:",
        type: "verse",
      },
    ],
  },
  {
    number: 22,
    title: "For All the Lord Has Done For Me",
    verses: [
      { line: "1 FOR all the Lord has done for me,", type: "verse" },
      { line: "I never will cease to praise Him;", type: "verse" },
      { line: "And for His grace so rich and free,", type: "verse" },
      { line: "I never will cease to praise Himl", type: "verse" },
      { line: "I never will cease to praise Him,", type: "chorus" },
      { line: "My Saviour, My Saviour;", type: "chorus" },
      { line: "I will never cease to praise Him,", type: "chorus" },
      { line: "He's done so much for me.", type: "chorus" },
      { line: "2 He gives me strength for every day,", type: "verse" },
      { line: "I never will cease to praise Him;", type: "verse" },
      { line: "He leads and guides me all the way,", type: "verse" },
      { line: "I never will cease to praise Him", type: "verse" },
      { line: "3 Although the world His love neglect,", type: "verse" },
      { line: "I never will cease to praise Him;", type: "verse" },
      { line: "I could not such a friend reject,", type: "verse" },
      { line: "I never will cease to praise Him.", type: "verse" },
      { line: "4 He saves me every day and hour,", type: "verse" },
      { line: "I never will cease to praise Him;", type: "verse" },
      { line: "Just now I feel His cleansing power,", type: "verse" },
      { line: "I never will cease to praise Him.", type: "verse" },
      { line: "5 While on my journey here below,", type: "verse" },
      { line: "I never will cease to praise Him;", type: "verse" },
      { line: "And when to that bright world I go,", type: "verse" },
      { line: "I never will cease to praise Him.", type: "verse" },
    ],
  },
  {
    number: 23,
    title: "O God of Bethel",
    verses: [
      { line: "1 O God of Bethel, by whose hand", type: "verse" },
      { line: "Thy people stil are fed.", type: "verse" },
      { line: "Who through his weary pilgrimage", type: "verse" },
      { line: "Hast all our fathers led.", type: "verse" },
      { line: "2 Our vows, our prayers we now prsent", type: "verse" },
      { line: "Before Thy throne of grace:", type: "verse" },
      { line: "God of our fathers, be the God", type: "verse" },
      { line: "of their succeeding race.", type: "verse" },
      { line: "3 Through each perplexing path of life", type: "verse" },
      { line: "Our wandering footsteps guide;", type: "verse" },
      { line: "Give us each day our daily bread,", type: "verse" },
      { line: "And raiment fit provide.", type: "verse" },
      { line: "4 O spread thy covering wings around, ", type: "verse" },
      { line: "Till all our wanderings cease,", type: "verse" },
      { line: "And at our Father's loved abode", type: "verse" },
      { line: "Our souls arrive in peace.", type: "verse" },
      { line: "5 Such blessings from Thy gracious hand", type: "verse" },
      { line: "Our humble prayers implore;", type: "verse" },
      { line: "And thou shalt be our chosen God,", type: "verse" },
      { line: "And portion evermore.", type: "verse" },
    ],
  },
  {
    number: 24,
    title: "Awake, My Soul  ",
    verses: [
      { line: "1 AWAKE my soul, and with the sun", type: "verse" },
      { line: "Thy daily stage of duty run;", type: "verse" },
      { line: "Shake of dull sloth, and joyful rise", type: "verse" },
      { line: "To pay thy morning sacrifice.", type: "verse" },
      { line: "2 Wake, and lift up thyself, my heart,", type: "verse" },
      { line: "And with the angels bear thy part,", type: "verse" },
      { line: "Who all night long unwearied sing", type: "verse" },
      { line: "High priase to the eternal King.", type: "verse" },
      { line: "3 Lord, I my vows to Thee renew ;", type: "verse" },
      { line: "Disperse my sins as morning dew;", type: "verse" },
      { line: "Guard my first springs of thought and will,", type: "verse" },
      { line: "And with Thyself my spirit fill.", type: "verse" },
      { line: "4 Direct, control, suggest, this day,", type: "verse" },
      { line: "All I design, or do, or say,", type: "verse" },
      { line: "That all my powers ,with all their might,", type: "verse" },
      { line: "In Thy sole glory may unite.", type: "verse" },
    ],
  },
  {
    number: 25,
    title: "Holy, Holy, Holy",
    verses: [
      { line: "1 Holy, holy, holy, Lord God Almighty!", type: "verse" },
      {
        line: "Early in the morning our song shall rise to Thee;",
        type: "verse",
      },
      { line: "Holy, holy, holy, merciful and mighty,", type: "verse" },
      { line: "God in three Persons, blessed Trinity!", type: "verse" },
      { line: "2 Holy, holy, holy! all the saints adore Thee,", type: "verse" },
      {
        line: "Casting down their golden crowns around the glassy sea;",
        type: "verse",
      },
      {
        line: "Cherubim and seraphim falling down before Thee,",
        type: "verse",
      },
      { line: "Which wert, and art, and evermore shalt be.", type: "verse" },
      {
        line: "3 Holy, holy, holy! though the darkness hide Thee,",
        type: "verse",
      },
      {
        line: "Though the eye of sinful man Thy glory may not see;",
        type: "verse",
      },
      { line: "Only Thou art holy! there is none beside Thee", type: "verse" },
      { line: "Perfect in power, in love and purity.", type: "verse" },
      { line: "4 Holy, holy, holy, Lord God Almighty!", type: "verse" },
      {
        line: "All Thy works shall praise Thy name, in earth, and sky, and sea;",
        type: "verse",
      },
      { line: "Holy, holy, holy, merciful and mighty,", type: "verse" },
      { line: "God in three Persons, blessed Trinity!", type: "verse" },
    ],
  },
  {
    number: 26,
    title: "All People That on Earth Do Dwell",
    verses: [
      {
        line: "1 ALL people that on earth do dwell,",
        type: "verse",
      },
      { line: "Sing to the Lord with cheerful voice;", type: "verse" },
      { line: "Him serve with mirth, His praise forth tell!", type: "verse" },
      { line: "Come ye before Him and rejoice.", type: "verse" },
      { line: "2 Know that the Lord is God indeed;", type: "verse" },
      { line: "Without our aid He did us make:", type: "verse" },
      { line: "We are His flock, He doth us feed,", type: "verse" },
      { line: "And for His sheep, He doth us take.", type: "verse" },
      { line: "3 Oh, enter then His gates with praise,", type: "verse" },
      { line: "Approach with joy His courts unto;", type: "verse" },
      { line: "Praise, laud, and bless His Name always,", type: "verse" },
      { line: "For it is seemly so to do.", type: "verse" },
      { line: "4 For why? the Lord our God is good.", type: "verse" },
      { line: "His mercy is for ever sure;", type: "verse" },
      { line: "His truth at all times firmly stood,", type: "verse" },
      { line: "And shall from age to age endure.", type: "verse" },
    ],
  },
  {
    number: 27,
    title: "Jesus Has Loved Me",
    verses: [
      { line: "1 Jesus has loved me—wonderful Saviour!", type: "verse" },
      { line: "Jesus has loved me, I cannot tell why;", type: "verse" },
      { line: "Came He to rescue sinners all worthless,", type: "verse" },
      { line: "My heart He conquered, for Him I would die.", type: "verse" },
      { line: "Glory to Jesus—wonderful Saviour!", type: "chorus" },
      { line: "Glory to Jesus, the One I adore;", type: "chorus" },
      {
        line: "Glory to Jesus—wonderful Saviour!",
        type: "chorus",
      },
      {
        line: "Glory to Jesus, and praise evermore.",
        type: "chorus",
      },
      {
        line: "2 Jesus has saved me—wonderful Saviour!",
        type: "verse",
      },
      {
        line: "Jesus has saved me, I cannot tell how;",
        type: "verse",
      },
      {
        line: "All that I know is He was my ransom,",
        type: "verse",
      },
      {
        line: "Dying on Calvary with thorns on His brow.",
        type: "verse",
      },
      {
        line: "3 Jesus will lead me—wonderful Saviour!",
        type: "verse",
      },
      {
        line: "Jesus will lead me, I cannot tell where;",
        type: "verse",
      },
      {
        line: "But I will follow through joy or sorrow,",
        type: "verse",
      },
      {
        line: "Sunshine or tempest, sweet peace or despair.",
        type: "verse",
      },
      {
        line: "4 Jesus will crown me—wonderful Saviour!",
        type: "verse",
      },
      {
        line: "Jesus will crown me, I cannot tell when;",
        type: "verse",
      },
      {
        line: "White throne of splendour, hail I with gladness,",
        type: "verse",
      },
      {
        line: "Crowned with the plaudits of angels and men.",
        type: "verse",
      },
    ],
  },
  {
    number: 28,
    title: "Cleansed in Our Saviour's Blood",
    verses: [
      {
        line: "1 Cleansed in our Saviour's precious blood,",
        type: "verse",
      },
      {
        line: "Filled with the fulness of our God,",
        type: "verse",
      },
      {
        line: "Walking by faith the path He trod,",
        type: "verse",
      },
      {
        line: "Hallelujah! Hallelujah!",
        type: "verse",
      },
      {
        line: "2 Leaning our heads on Jesus' breast,",
        type: "verse",
      },
      {
        line: "Knowing the joy of that sweet rest,",
        type: "verse",
      },
      {
        line: "Finding in Him the chief, the best,",
        type: "verse",
      },
      {
        line: "Hallelujah! Hallelujah!",
        type: "verse",
      },
      {
        line: "3 Kept by His power from day to day,",
        type: "verse",
      },
      {
        line: "Held by His hand, we cannot stray,",
        type: "verse",
      },
      {
        line: "Glory to glory all the way,",
        type: "verse",
      },
      {
        line: "Hallelujah! Hallelujah!",
        type: "verse",
      },
      {
        line: "4 Living in us His own pure life,",
        type: "verse",
      },
      {
        line: "Giving us rest from inward strife,",
        type: "verse",
      },
      {
        line: "From strength to strength, from death to life,",
        type: "verse",
      },
      {
        line: "Hallelujah! Hallelujah!",
        type: "verse",
      },
      {
        line: "5 Oh, what a Saviour we have found!",
        type: "verse",
      },
      {
        line: "Well may we make the world resound,",
        type: "verse",
      },
      {
        line: "With one continual, joyous sound,",
        type: "verse",
      },
      {
        line: "Hallelujah! Hallelujah!",
        type: "verse",
      },
    ],
  },
];

export default songs;
