import { title } from "process";

const songs = [
  {
    number: 1,
    title: ".  All Hail the Power of Jesus' Name",
    verses: [
      "1 ALL hail the power of Jesu’s name,",
      " Let angels prostrate fall;",
      " Bring forth the royal diadem,",
      "And crown Him Lord of all.",
      "2. Crown Him, ye martyrs of your God,",
      " Who from His altar call;",
      " Extol the stem of Jesse’s rod,;",
      " And crown Him Lord of all.",
      "3. Ye chosen seed of Israel’s race,",
      " A remnant weak and small,",
      " Hail Him Who saves you by His grace,",
      " And crown Him Lord of all,",
      "4. Ye Gentile sinners, ne’er forget",
      " The wormwood and the gall;",
      "Go, spread your trophies a His feet,:",
      "And crown Him Lord of all.",
      "5. Let every kindred, every tribe,;",
      "On this terrestrial ball,",
      "To Him all majesty ascribe,",
      "And crown Him Lord of all.",
      "6. O that with yonder sacred throng",
      "We at His feet may fall,",
      "Join in the everlasting song",
      "And crown Him Lord of all.",
    ],
  },
  {
    number: 2,
    title: ". Break Thou the Bread of Life",
    verses: [
      "1 BREAK Thou the bread of life,",
      "Dear Lord, to me,",
      "As Thou didst break the loaves",
      "Beside the sea.",
      "Beyond the sacred page",
      "I seek Thee, Lord;",
      "My spirit pants for Thee,",
      "O Living Word!",
      "2 Break Thou the bread of life,:",
      "O Lord, to me,",
      "That hid within my heart",
      "Thy Word may be:",
      "Mould Thou each inward thought,",
      "From self set free,",
      "And let my steps be all",
      "Controlled by Thee.",
      "3 Open Thy Word of Truth,",
      "That I may see",
      "Thy message written clear",
      "And plain for me;",
      "Then in sweet fellowship",
      "Walking with Thee,",
      "Thine image on my life",
      "Engraved will be.",
      "4 Bless Thou the truth, dear Lord,",
      "To me, to me,",
      "As Thou didst bless the bread",
      "By Galilee:",
      "Then shall all bondage cease,",
      "All fetters fall;",
      "And I shall find my peace,",
      "My All in All!",
    ],
  },
  {
    number: 3,
    title: ". We Come Before Thy Throne Today",
    verses: [
      "1 WE come before Thy throne to-day,",
      "Thy promised presence claim;",
      "O come and enter now our hearts,",
      "And set our souls aflame.",
      "Lord, send Thy blessing, Lord, send Thy blessing,",
      "Lord, send Thy blessing on our waiting souls.",
      "2 We know that Thou art present here,",
      "Thy grace to us reveal;",
      "We fain would know Thy blessed will,",
      "Thy holy presence feel,",
      "3 0 send to us Thy quickening power,",
      "All guilt and dross remove;",
      "O let our waiting hearts be filled,",
      "Dear Saviour, with Thy love.",
      "4 Accept the homage that we bring,",
      "O Lord, we humbly pray;",
      "Bestow Thy richest blessings now,",
      "And meet with us to-day.",
    ],
  },
  {
    number: 4,
    title: ". The Name of Jesus is So Sweet",
    verses: [
      "1 THE name of Jesus is so sweet,",
      "I love its music to repeat;",
      "It makes my joys full and complete,",
      "The precious name of Jesus.",
      "“Jesus,” oh, how sweet the name!",
      "Jesus,” every day the same;",
      "Jesus,” let all saints proclaim",
      "Its worthy praise for ever.",
      "2 I love the name of Him Whose heart",
      "Knows all my griefs and bears a part;",
      "Who bids all anxious fears depart—",
      "I love the name of Jesus,",
      "3 That name I fondly love to hear,",
      "It never fails my heart to cheer,",
      "Its music dries the falling tear;",
      "Exalt the name of Jesus.",
      "4 No word of man can ever tell",
      "How sweet the name I love so well;",
      "Oh, let its praises ever swell!",
      "Oh, praise the name of Jesus",
    ],
  },
  {
    number: 5,
    title: ". When Upon Life’s Billows",
    verses: [
      "1 WHEN upon life’s billows you are tempest tossed,",
      "When you are discouraged, thinking all is lost",
      "Count your many blessings, name them one by one,",
      "And it will surprise you what the Lord hath done.",
      "Count your blessings, name them one by one,",
      "Count your blessings, see what God hath done;",
      "Count your blessings, name them one by one,",
      "And it will surprise you what the Lord hath done.",
      "2 Are you ever burdened with a load of care?",
      "Does the cross seem-heavy you are called to bear?",
      "Count your many blessings, every doubt will fly,",
      "And you will be singing as the days go by.",
      "3 When you look at others with their lands and gold,",
      "Think that Christ has promised you His wealth untold,",
      "Count your many blessings, money cannot buy",
      "Your reward in heaven, nor your home on high.",
      "4 So amid the conflict, Whether great or small,",
      "Do not be discouraged, God is over all,",
      "Count your many blessings, angels will attend,",
      "Help and comfort give you to your journey’s end.",
    ],
  },
  {
    number: 6,
    title: ". God is Here, and That To Bless Us",
    verses: [
      "1 GOD is here, and that to bless us",
      "With the Spirit’s quickening power:",
      "See, the cloud already bending,",
      "Waits to drop the grateful shower.",
      "Let it come, O Lord, we pray Thee,",
      "Let the shower of blessing fall;",
      "We are waiting, we are waiting,",
      "Oh, revive the hearts of all.",
      "2 God is here! we feel His presence",
      "In this consecrated place;",
      "But we need the soul refreshing",
      "Of His free, unbounded grace.",
      "3 God is here! oh, then, believing,",
      "Bring to Him our one desire,",
      "That His love may now be kindled,",
      "Till its flame each heart inspire.",
      "4 Saviour, grant the prayer we offer,",
      "While in simple faith we bow,",
      "From the windows of Thy mercy",
      "Pour us out a bleessing now.",
    ],
  },
  {
    number: 7,
    title: ". To God be the Glory",
    verses: [
      "1 TO God be the glory, great things He hath done,",
      "So loved He the world that He gave us His Son,",
      "Who yielded His life an atonement for sin,",
      "And opened the Life Gate that all may o in.",
      "Praise the Lord, praise the Lord,",
      "Let the earth hear His voice;",
      "Praise the Lord, praise the Lord,",
      "Let the people rejoice.",
      "O come to the Father, through Jesus the Son,",
      "And give Hin the glory, great things He hath done.",
      "2 0 perfect redemption, the purchase of blood,",
      "To every believer the promise of God;",
      "The vilest offender who truly believes,",
      "That moment from Jesus a pardon receives.",
      "3 Great things He hath taught us, great things He hath done,",
      "And great our rejoicing through Jesus the Son;",
      "But purer, and higher, and greater will be-",
      "Our wonder, our transport when Jesus we see,",
    ],
  },
  {
    number: 8,
    title: ". Who is on the Lord's Side?",
    verses: [
      "1 WHO is on the Lord’s side?",
      "Who will serve the King?",
      "Who will be His helpers,",
      "Other lives to bring?",
      "Who will leave the world’s side?",
      "Who will face the foe?",

      "Who is on the Lord’s side",
      "Who for Him will go?",
      "By Thy call of mercy,",

      "By Thy grace divine,",
      "We are on the Lord's side,",
      "Saviour, we are Thine!",
      "2 Not for weight of glory,",
      "Not for crown and palm,",
      "Enter we the army,",
      "Raise the warrior psalm;",
      "But for love that claimeth",
      "Lives for whom He died:",
      "He whom Jesus nameth",
      "Must be on His side!",
      "By Thy love constraining,",
      "By Thy grace divine,",
      "We are on the Lord’s side,",
      "Saviour, we are Thine!",
      "3 Jesus, Thou hast bought us,",
      "Not with gold or gem,",
      "But with Thine own life-blood",
      "For Thy diadem;",
      "With Thy blessing filling",
      "All who come to Thee,",
      "Thou hast made us willing,",
      "Thou hast made us free.",
      "By Thy grand redemption,",
      "By Thy grace divine,",
      "We are on the Lord’s side,",
      "Saviour, we are Thine!",
      "4 Fierce may be the conflict,",
      "Strong may be the foe;",
      "But the King’s own army",
      "None can overthrow:",
      "Round His standard ranging,",
      "Victory is secure,",
      "For His truth unchanging",
      "Makes the triumph sure,",
      "Joyfully enlisting,",
      "By Thy grace divine,",
      "We are on the Lord’s side",
      "Saviour, we are Thine!",
    ],
  },
  {
    number: 9,
    title: ". I Must Have the Saviour With Me",
    verses: [
      "1 I MUST have the Saviour with me",
      "For I dare not walk alone,",
      "I must feel His presence near me,",
      "And His arm around me thrown,",
      "Then my soul ... shall fear no ill ...,",
      "Let Him lead .... me where He will ...",
      "I will go without a murmur,",
      "And His footsteps follow still.",
      "2 I must have the Saviour with me",
      "For my faith, at best, is weak",
      "He can whisper words of comfort",
      "That no other voice can speak.",
      "3 I must have the Saviour with me",
      "In the onward march of life,",
      "Through the tempest and the sunshine",
      "Through the battle and the strife",
      "4 I must have the Saviour with me",
      "And His eye the way must guide",
      "Till I reach the vale of Jordan",
      "Till I cross the rolling tide",
    ],
  },
  {
    number: 10,
    title: ". Here in Thy Name We are Gathered",
    verses: [
      "1 HERE in Thy name we are gathered,",
      "Come and revive us, O Lord;",
      "There shall be showers of blessing,",
      "Thou hast declared in Thy word.",
      "Oh, graciously hear us,",
      "Graciously hear us, we pray",
      "Pour from Thy windows upon us",
      "Showers of blessing to-day.",
      "2 Oh! that the showers of blessing",
      "Now on our sows may descend,",
      "While at the footstool of mercy",
      "Pleading Thy promise we bend!",
      "3 There shall be showers of blessing,",
      "Promise that never can fail;",
      "Thou wilt regard our petition;",
      "Surely our faith will prevail.",
      "4 Showers of blessing, we need them,",
      "Showers of blessing from Thee;",
      "Showers of blessing, oh, grant them,",
      "Thine all the glory shall be.",
    ],
  },
  {
    number: 11,
    title: ". My Song Shall Be of Jesus",
    verses: [
      "1 MY song shall be of Jesus,",
      "His mercy crowns my days,",
      "He fills my cup with blessings,",
      "And tunes my heart to praise;",
      "My song shall be of Jesus,",
      "The precious Lamb of God,",
      "Who gave Himself my ransom,",
      "And bought me with His blood.",
      "2 My song shall be of Jesus,",
      "When sitting at His feet,",
      "I call to mind His goodness,",
      "In meditation sweet:",
      "My song shall be of Jesus,",
      "Whatever ill betide;",
      "I'll sing the grace that saves me,",
      "And keeps me at His side,",
      "3 My song shall be of Jesus,",
      "While pressing on my way,",
      "To reach the blissful region",
      "Of pure and perfect day;",
      "And when my soul shall enter",
      "The gate of Eden fair,",
      "A song of praise to Jesus",
      "I'll sing for ever there.",
    ],
  },
  {
    number: 12,
    title: ". Praise Him, Jesus Our Blessed Redeemer",
    verses: [
      "1 PRAISE Him, praise Him, Jesus, our blessed Redeemer,",
      "Sing, O earth, His wonderful love proclaim,",
      "Hail Him! hail Him! highest archangels in glory,",
      "Strength and honour give to His holy name.",
      "Like a shepherd Jesus will guard His children,",
      "In His arms He carries them all day long.",
      "O ye saints that dwell on the mountain of Zion,",
      "Praise Him! praise Him! ever in joyful song.",
      "2 Praise Him, praise Him, Jesus, our blessed Redeemer,",
      "For our sins He suffered and bled and died;",
      "He, our rock, our hope of eternal salvation,",
      "Hail Him! hail Him! Jesus the crucified.",
      "Loving Saviour, meekly enduring sorrow,",
      "Crowned with thorns that cruelly pierced His brow;",
      "Once for us rejected, despised, and forsaken,",
      "Prince of Glory, ever triumphant now.",
      "3 Praise Him, praise Him, Jesus, our blessed Redeemer,",
      "Heavenly portals, loud with hosannahs ring,",
      "Jesus, Saviour, reigneth for ever and ever,",
      "Crown Him, crown Him, Prophet and Priest and King!",
      "Death is vanquished! tell it with joy ye faithful,",
      "Where is now thy victory, boasting grave?",
      "Jesus lives! no longer thy portals are cheerless,",
      "Jesus lives, the mighty and strong to save.",
    ],
  },
  {
    number: 13,
    title: ". Standing on the Promises of Christ",
    verses: [
      "1 STANDING on the promises of Christ our King,",
      "Through eternal ages let His praises ring:",
      "Glory in the highest, I will shout and sing,",
      "Standing on the promises of God.",
      "Stand....ing, stand....ing,",
      "Standing on the promises of God my Saviour,",
      "Stand....ing, stand....ing,",
      "I'm standing on the promises of God.",
      "2 Standing on the promises that cannot fail,",
      "When the howling storms of doubt and fear assail,",
      "By the living word of God I shall prevail,",
      "Standing on the promises of God.",
      "3 Standing on the promises I now can see",
      "Perfect, present cleansing in the blood for me;",
      "Standing in the liberty where Christ makes free,",
      "Standing on the promises of God.",
      "4 Standing on the promises of Christ the Lord",
      "Bound to Him eternally by love’s strong cord,",
      "Overcoming daily with the Spirit’s sword,",
      "Standing on the promises of God.",
    ],
  },
  {
    number: 14,
    title: ". The Wondrous Work the Lord Has Done",
    verses: [
      "1 THE wondrous work the Lord has done",
      "Let every voice proclaim!",
      "And for the work of grace begun;",
      "The wondrous battle fought and won,",
      "Give glory to His name!",
      "We pleaded for the Spirit,",
      "He came in mighty power!",
      "We pleaded for the droppings,",
      "And, lo, He sent the shower!",
      "2 Unto the Lord doth praise belong",
      "O tell it everywhere!",
      "Let every ransomed soul prolong",
      "The loud hosannah of the song",
      "The Lord doth answer prayer!",
      "3 We'll sing the power of Jesus’ name,",
      "And His atoning blood;",
      "To-day and evermore the same,",
      "The vilest sinner to reclaim,",
      "And bring him back to God.",
      "4 Let every heart and every tongue",
      "As one united host",
      "Praise God for what His arm hath done",
      "Praise God the Father, God the Son,",
      "And God the Holy Ghost",
    ],
  },
  {
    number: 15,
    title: ". Come, O My Soul",
    verses: [
      "COME, O my soul, my every power awaking,",
      "Look unto Him whose goodness crowns thy days;",
      "While into song angelic choirs are breaking,",
      "O let thy voice its thankful tribute raise,",
      "Tell how alone the path of death He trod;",
      "Tell how He lives, thine Advocate with God;",
      "Lift up thy voice, while heaven's triumphant throng",
      "Swell at His feet the everlasting song.",
      "2 Think O my soul, how patiently He sought thee,",
      "Far, far away upon the mountains steep,",
      "Then in His arms how tenderly He brought thee,",
      "Home to His fold a weary, wandering sheep.",
      "3 Sing, O my soul, and let thy pure devotion",
      "Rise to His throne, thy Sayiour, Friend, and Guide;",
      "Sing of His love, that, like a mighty ocean,",
      "Flows unto thee, and all the world beside.",
      "4 Soon, O my soul, thine earthly house forsaking,",
      "Soon shalt thou rise the better land to see",
      "Then will thy harp, a nobler strain awaking,",
      "Praise Him who died to purchase life for thee.",
    ],
  },
];

export default songs;
